// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package simple_store_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Country struct {
	CountryID     int64
	CountryCode   pgtype.Text
	CountryName   pgtype.Text
	ContinentName pgtype.Text
}

type Merchant struct {
	MerchantID        int64
	MerchantFirstName pgtype.Text
	MerchantLastName  pgtype.Text
	CountryID         pgtype.Int8
	UserID            pgtype.Int8
}

type OrderHeader struct {
	OrderHeaderID int64
	OrderDate     pgtype.Timestamp
	OrderStatusID pgtype.Int8
	UserID        pgtype.Int8
	MerchantID    pgtype.Int8
}

type OrderLine struct {
	LineID        int64
	ProductID     pgtype.Int8
	OrderHeaderID pgtype.Int8
	Quantity      pgtype.Int4
}

type OrderStatus struct {
	OrderStatusID   int64
	OrderStatusName pgtype.Text
}

type Product struct {
	ProductID       int64
	ProductName     pgtype.Text
	ProductPrice    pgtype.Int4
	ProductStatusID pgtype.Int8
	MerchantID      pgtype.Int8
}

type ProductStatus struct {
	ProductStatusID int64
	StatusName      pgtype.Text
}

type User struct {
	UserID    int64
	FirstName pgtype.Text
	LastName  pgtype.Text
	Salt      pgtype.Text
	Password  pgtype.Text
	Email     pgtype.Text
	CountryID pgtype.Int8
}
