// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package simple_store_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteCountries(ctx context.Context, countryID int64) error
	DeleteMerchant(ctx context.Context, merchantID int64) error
	DeleteOrderHeader(ctx context.Context, orderHeaderID int64) error
	DeleteOrderLines(ctx context.Context, lineID int64) error
	DeleteOrderLinesUsingOrderHeaderID(ctx context.Context, orderHeaderID pgtype.Int8) error
	DeleteOrderStatus(ctx context.Context, orderStatusID int64) error
	DeleteProduct(ctx context.Context, productID int64) error
	DeleteProductStatus(ctx context.Context, productStatusID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	GetAllCountries(ctx context.Context) ([]Country, error)
	GetAllCountriesByPage(ctx context.Context, arg GetAllCountriesByPageParams) ([]Country, error)
	GetAllMerchants(ctx context.Context) ([]Merchant, error)
	GetAllOrders(ctx context.Context) ([]OrderHeader, error)
	GetAllProducts(ctx context.Context) ([]Product, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetCountryByID(ctx context.Context, countryID int64) (Country, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (GetUserByEmailRow, error)
	InsertCountry(ctx context.Context, arg InsertCountryParams) (Country, error)
	InsertMerchant(ctx context.Context, arg InsertMerchantParams) (Merchant, error)
	InsertOrderHeader(ctx context.Context, arg InsertOrderHeaderParams) (OrderHeader, error)
	InsertOrderLines(ctx context.Context, arg InsertOrderLinesParams) (OrderLine, error)
	InsertOrderStatus(ctx context.Context, orderStatusName pgtype.Text) (OrderStatus, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error)
	InsertProductStatus(ctx context.Context, statusName pgtype.Text) (ProductStatus, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error)
	UpdateOrderHeader(ctx context.Context, arg UpdateOrderHeaderParams) (OrderHeader, error)
	UpdateOrderLine(ctx context.Context, arg UpdateOrderLineParams) (OrderLine, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (OrderStatus, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (ProductStatus, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
